name: Go

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set-up go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: tidy
        run: go mod tidy
      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          repo-checkout: false
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          skip-cache: true
      - name: test race
        run: go test -race ./...
